parameters:
- name: ci_pool
  displayName: Pool based on own Agents
  type: string
  default: phx-automation-ci
  # values:
  # - phx-automation-ci-1


trigger:
- master

pool: 
  name: phx-automation-ci
  
  # demands:
  # - myCustomCapability   # check for existence of capability
  # - agent.os -equals Darwin  # check for specific string in capability

  # vmImage: string # name of the VM image you want

# pool:
#   vmImage: 'ubuntu-latest'

stages:
- stage: The Build stage
  displayName: The Build
  jobs:
  - job: BuildJob
    displayName: The BuildJob
    pool: ${{ paramenters.ci_pool }}
    steps:
    - script: echo Building!
- stage: Test
  displayName: The Test stage
  jobs:
  - job: TestOnWindows
    displayName: The Test on Windows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    displayName: The Test on Linux
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  displayName: The Building stage
  jobs:
  - job: Deploy
    displayName: The Deployment
    steps:
    - script: echo Deploying the code!