parameters:
- name: ci_pool
  displayName: Pool based on own Agents
  type: string
  default: phx-automation-ci
  # values:
  # - phx-automation-ci-1

- name: cd_pool
  displayName: Deployment Pool based on own Agents
  type: string
  default: test-deployment-group-0


trigger:
- master

# pool: 
#   name: ${{ parameters.ci_pool }}

stages:
- stage: Build
  displayName: The Build Stage
  jobs:
  - job: BuildJob
    displayName: The BuildJob
    pool: ${{ parameters.ci_pool }}
    steps:
    - script: echo Building!
- stage: Test
  displayName: The Test stage
  jobs:
  - job: TestOnWindows
    displayName: The Test on Windows
    #pool: ${{ parameters.windows_pool }} 
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    displayName: The Test on Linux
    #pool: ${{ parameters.linux_pool }} 
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  displayName: The Building stage
  jobs:
  - job: Deploy
    displayName: The Deployment
    steps:
    - script: echo Deploying the code!