# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  name: phx-automation-ci
  
  # demands:
  # - myCustomCapability   # check for existence of capability
  # - agent.os -equals Darwin  # check for specific string in capability

  # vmImage: string # name of the VM image you want

# pool:
#   vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'